package com.goldhouse.server.mapper;

import com.goldhouse.server.dto.orderDTO.OrderRequestDTO;
import com.goldhouse.server.dto.orderDTO.OrderResponseDTO;
import com.goldhouse.server.model.Customer;
import com.goldhouse.server.model.Order;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface OrderMapper {

    @Mapping(target = "id", ignore = true)           // Auto-generated by @OrderId
    @Mapping(target = "customer", source = "customer") // Passed separately
    @Mapping(source = "orderRequestDTO.weight", target = "weight")
    @Mapping(source = "orderRequestDTO.result", target = "result")
    @Mapping(source = "orderRequestDTO.wastage", target = "wastage")
    @Mapping(source = "orderRequestDTO.stampNo", target = "stampNo")
    @Mapping(source = "orderRequestDTO.orderDate", target = "orderDate")
    @Mapping(source = "orderRequestDTO.orderTime", target = "orderTime")
    @Mapping(source = "orderRequestDTO.deliverDate", target = "deliverDate")
    @Mapping(source = "orderRequestDTO.deliverTime", target = "deliverTime")
    @Mapping(source = "orderRequestDTO.orderStatus", target = "orderStatus")
    Order toEntity(OrderRequestDTO orderRequestDTO, Customer customer);

    @Mapping(source = "id", target = "orderId")      // id → orderId rename
    OrderResponseDTO toResponseDTO(Order order);
}